In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
index = pd.date_range('1/1/2000', periods=8)

In [4]:
s = pd.Series(np.random.randn(5), index = ['a', 'b', 'c', 'd', 'e'])

In [5]:
df = pd.DataFrame(np.random.randn(8, 3), index=index, columns=['A', 'B', 'C'])

In [6]:
wp = pd.Panel(np.random.randn(2, 5, 4), 
              items=['Item1', 'Item2'], 
              major_axis = pd.date_range('1/1/2000', periods=5),
              minor_axis = ['A', 'B', 'C', 'D'])

# 1 Head and Tail

Métodos Utilizados para visualização de dados reduzidas (no padrão 5 registros). Um exibe os 5 primeiros e o outro os 5 últimos

In [7]:
long_series = pd.Series(np.random.randn(1000))

In [8]:
long_series.head() # 5  primeiros registros

0    0.319443
1    0.660056
2    0.411565
3    0.550423
4   -0.389753
dtype: float64

In [9]:
long_series.tail() # 5 últimos registros

995   -0.208685
996    0.168263
997    0.533029
998    0.878315
999   -0.051018
dtype: float64

In [10]:
# modificando a quanditrade:
long_series.tail(3) 

997    0.533029
998    0.878315
999   -0.051018
dtype: float64

# 2 Attributes and the raw ndarray(s)

In [11]:
df[:2]

A         B         C
2000-01-01 -0.504617 -0.078000  0.294475
2000-01-02  0.600528 -0.949265 -0.500694

In [12]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [13]:
df.columns = [x.lower() for x in df.columns]; df

a         b         c
2000-01-01 -0.504617 -0.078000  0.294475
2000-01-02  0.600528 -0.949265 -0.500694
2000-01-03 -0.876985  1.528629 -0.029250
2000-01-04  0.292229 -0.907049 -0.536447
2000-01-05 -1.239547 -0.054182 -0.814006
2000-01-06  0.620018  1.018885  0.124613
2000-01-07  0.933291  0.636022 -0.946616
2000-01-08 -1.867705  0.827706 -0.718978

In [14]:
s

a   -0.127402
b   -2.203597
c    2.821316
d   -2.028091
e    1.431575
dtype: float64

In [15]:
s.values

array([-0.12740235, -2.20359687,  2.82131587, -2.02809145,  1.43157524])

In [16]:
df.head()

a         b         c
2000-01-01 -0.504617 -0.078000  0.294475
2000-01-02  0.600528 -0.949265 -0.500694
2000-01-03 -0.876985  1.528629 -0.029250
2000-01-04  0.292229 -0.907049 -0.536447
2000-01-05 -1.239547 -0.054182 -0.814006

In [17]:
df.values

array([[-0.50461743, -0.07800026,  0.29447461],
       [ 0.60052848, -0.94926506, -0.50069415],
       [-0.87698498,  1.52862918, -0.0292498 ],
       [ 0.29222889, -0.90704893, -0.53644655],
       [-1.23954654, -0.05418189, -0.81400555],
       [ 0.62001757,  1.01888519,  0.12461316],
       [ 0.93329075,  0.63602171, -0.94661613],
       [-1.86770468,  0.82770598, -0.71897762]])

In [18]:
wp

<class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 5 (major_axis) x 4 (minor_axis)
Items axis: Item1 to Item2
Major_axis axis: 2000-01-01 00:00:00 to 2000-01-05 00:00:00
Minor_axis axis: A to D

In [19]:
wp.values

array([[[-0.73188957,  3.94247023,  0.88798437, -0.3964831 ],
        [ 1.53273463, -0.0937379 , -1.34955277, -0.91851645],
        [-1.92664581,  0.73115313,  1.97169314, -1.06482034],
        [ 0.91901217,  1.71834719,  0.02218841,  0.0762335 ],
        [ 1.15672858, -0.56900455, -1.34633398,  0.63229909]],

       [[ 2.02668449, -1.28341664, -0.31789861, -0.68333541],
        [-0.50678179, -1.11169089,  2.09523642,  0.10388466],
        [-0.58967505,  0.42716006,  0.19818194,  0.28474702],
        [-0.7411608 , -0.75474965, -0.28831361,  0.47862693],
        [-1.21333751, -0.92551585, -0.37321727,  0.34977535]]])

# 3 Matching / broadcasting behavior

In [20]:
df = pd.DataFrame({
    'one': pd.Series(np.random.randn(3), index=['a', 'b', 'c']),
    'two': pd.Series(np.random.randn(4), index=['a', 'b', 'c', 'd']),
    'three': pd.Series(np.random.randn(3), index=['b', 'c', 'd'])
})
df

one     three       two
a  0.251360       NaN  0.175308
b -0.415292 -0.248493 -0.860320
c -0.761420  0.430212 -1.153337
d       NaN  0.664440  0.012675

In [21]:
row = df.iloc[1]; row

one     -0.415292
three   -0.248493
two     -0.860320
Name: b, dtype: float64

In [22]:
column = df['two']; column

a    0.175308
b   -0.860320
c   -1.153337
d    0.012675
Name: two, dtype: float64

In [23]:
df.sub(row, axis='columns')

one     three       two
a  0.666652       NaN  1.035628
b  0.000000  0.000000  0.000000
c -0.346128  0.678704 -0.293017
d       NaN  0.912933  0.872995

In [24]:
df.sub(row, axis=1)

one     three       two
a  0.666652       NaN  1.035628
b  0.000000  0.000000  0.000000
c -0.346128  0.678704 -0.293017
d       NaN  0.912933  0.872995

In [25]:
df.sub(column, axis='index')

one     three  two
a  0.076052       NaN  0.0
b  0.445028  0.611828  0.0
c  0.391917  1.583549  0.0
d       NaN  0.651766  0.0

In [26]:
df.sub(column, axis=0)

one     three  two
a  0.076052       NaN  0.0
b  0.445028  0.611828  0.0
c  0.391917  1.583549  0.0
d       NaN  0.651766  0.0

In [27]:
dfmi = df.copy()

In [28]:
dfmi.index = pd.MultiIndex.from_tuples([
    (1, 'a'), (1, 'b'), (1, 'c'), (2, 'a')
], names=['first', 'second'])

In [29]:
dfmi

one     three       two
first second                              
1     a       0.251360       NaN  0.175308
      b      -0.415292 -0.248493 -0.860320
      c      -0.761420  0.430212 -1.153337
2     a            NaN  0.664440  0.012675

In [30]:
dfmi.sub(column, axis=0, level='second')

one     three       two
first second                              
1     a       0.076052       NaN  0.000000
      b       0.445028  0.611828  0.000000
      c       0.391917  1.583549  0.000000
2     a            NaN  0.489132 -0.162633

In [31]:
wp

<class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 5 (major_axis) x 4 (minor_axis)
Items axis: Item1 to Item2
Major_axis axis: 2000-01-01 00:00:00 to 2000-01-05 00:00:00
Minor_axis axis: A to D

In [32]:
major_mean = wp.mean(axis='major'); major_mean

Item1     Item2
A  0.189988 -0.204854
B  1.145846 -0.729643
C  0.037196  0.262798
D -0.334257  0.106740

In [33]:
wp.sub(major_mean, axis='major')

<class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 5 (major_axis) x 4 (minor_axis)
Items axis: Item1 to Item2
Major_axis axis: 2000-01-01 00:00:00 to 2000-01-05 00:00:00
Minor_axis axis: A to D

In [34]:
s = pd.Series(np.arange(10)); s

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32

In [35]:
div, rem = divmod(s, 3)

In [36]:
div

0    0
1    0
2    0
3    1
4    1
5    1
6    2
7    2
8    2
9    3
dtype: int32

In [37]:
rem

0    0
1    1
2    2
3    0
4    1
5    2
6    0
7    1
8    2
9    0
dtype: int32

In [38]:
idx = pd.Index(np.arange(10)); idx

Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int64')

In [39]:
div, rem = divmod(idx, 3)

In [40]:
div

Int64Index([0, 0, 0, 1, 1, 1, 2, 2, 2, 3], dtype='int64')

In [41]:
rem

Int64Index([0, 1, 2, 0, 1, 2, 0, 1, 2, 0], dtype='int64')

In [42]:
div, rem = divmod(s, [2, 2, 3, 3, 4, 4, 5, 5, 6, 6])

In [43]:
div

0    0
1    0
2    0
3    1
4    1
5    1
6    1
7    1
8    1
9    1
dtype: int32

In [44]:
rem

0    0
1    1
2    2
3    0
4    0
5    1
6    1
7    2
8    2
9    3
dtype: int32

# 4 Boolean Reductions

In [45]:
df

one     three       two
a  0.251360       NaN  0.175308
b -0.415292 -0.248493 -0.860320
c -0.761420  0.430212 -1.153337
d       NaN  0.664440  0.012675

In [46]:
(df > 0).all()

one      False
three    False
two      False
dtype: bool

In [47]:
(df > 0).any()

one      True
three    True
two      True
dtype: bool

In [48]:
(df > 0).any().any()

True

In [49]:
df.empty

False

In [50]:
dftmp = pd.DataFrame(columns=list('ABC')); dftmp

Empty DataFrame
Columns: [A, B, C]
Index: []

In [51]:
dftmp.empty # Retorna treu porque não consta nenhuma linha de dados

True

In [52]:
pd.Series([True]).bool()

True

In [53]:
pd.Series([False]).bool()

False

In [54]:
pd.DataFrame([True]).bool()

True

In [55]:
pd.DataFrame([False]).bool()

False

# 5 Comparing if objects are equivalent

In [56]:
df + df == df * 2

one  three   two
a   True  False  True
b   True   True  True
c   True   True  True
d  False   True  True

In [57]:
(df + df == df * 2).all()

one      False
three    False
two       True
dtype: bool

In [58]:
# Tem resultados False porque a comparação de NaN(not a number) não produz resultado True
np.nan == np.nan

False

In [59]:
# Para contornar esse problema, utiliza-se o equals()
(df+df).equals(df*2)

True

In [60]:
# A ordem dos dados importa para que uma base seja igual a outra através do método equals()
df1 = pd.DataFrame({'col': ['foo', 0, np.nan]})
df2 = pd.DataFrame({'col': [np.nan, 0, 'foo']}, index=[2,1,0])

In [61]:
df1

col
0  foo
1    0
2  NaN

In [62]:
df2

col
2  NaN
1    0
0  foo

In [63]:
df1.equals(df2)

False

In [64]:
# Norte acora com o indice organizado
df1.equals(df2.sort_index())

True

# 6 Comparing array-like objects

In [65]:
pd.Series(['foo', 'bar', 'baz']) == 'foo'

0     True
1    False
2    False
dtype: bool

In [66]:
pd.Index(['foo', 'bar', 'baz']) == 'foo'

array([ True, False, False], dtype=bool)

In [67]:
pd.Series(['foo', 'bar', 'baz']) == pd.Series(['foo', 'bar', 'qux'])

0     True
1     True
2    False
dtype: bool

In [68]:
pd.Series(['foo', 'bar', 'baz']) == np.array(['foo', 'bar', 'qux'])

0     True
1     True
2    False
dtype: bool

# 7 Combining overlapping data sets

Combinando conjuntos de dados sobrepostos

In [69]:
df1 = pd.DataFrame({
    'A': [1., np.nan, 3., 5., np.nan],
    'B': [np.nan, 2., 3., np.nan, 6.]
})

In [70]:
df2 = pd.DataFrame({
    'A': [5., 2., 4., np.nan, 3., 7.],
    'B': [np.nan, np.nan, 3., 4., 6., 8.]
})

In [71]:
df1

A    B
0  1.0  NaN
1  NaN  2.0
2  3.0  3.0
3  5.0  NaN
4  NaN  6.0

In [72]:
df2

A    B
0  5.0  NaN
1  2.0  NaN
2  4.0  3.0
3  NaN  4.0
4  3.0  6.0
5  7.0  8.0

In [73]:
df1.combine_first(df2) # Este método é muito útil

A    B
0  1.0  NaN
1  2.0  2.0
2  3.0  3.0
3  5.0  4.0
4  3.0  6.0
5  7.0  8.0

## 7.1 General DataFrame Combine

Combinando funções em conjunto de dados sobrepostos

In [74]:
# Só vai efetuar a combinação em celunas NaN (not a number)
combiner = lambda x, y: np.where(pd.isna(x), y, x) 

In [75]:
df1

A    B
0  1.0  NaN
1  NaN  2.0
2  3.0  3.0
3  5.0  NaN
4  NaN  6.0

In [76]:
df2

A    B
0  5.0  NaN
1  2.0  NaN
2  4.0  3.0
3  NaN  4.0
4  3.0  6.0
5  7.0  8.0

In [77]:
df1.combine(df2, combiner)

A    B
0  1.0  NaN
1  2.0  2.0
2  3.0  3.0
3  5.0  4.0
4  3.0  6.0
5  7.0  8.0

# 8 Estatísticas Descritivas

In [78]:
df

one     three       two
a  0.251360       NaN  0.175308
b -0.415292 -0.248493 -0.860320
c -0.761420  0.430212 -1.153337
d       NaN  0.664440  0.012675

In [79]:
df.mean(0) # traz a média por colunas

one     -0.308451
three    0.282053
two     -0.456419
dtype: float64

In [80]:
df.mean(1) # tráz a média por linhas

a    0.213334
b   -0.508035
c   -0.494848
d    0.338557
dtype: float64

In [81]:
# Outro exemplo para facilitar a leitura
dfmean = pd.DataFrame({
    'A': [2., 3., 7.],
    'B': [2., 3., 4.]
})
dfmean

A    B
0  2.0  2.0
1  3.0  3.0
2  7.0  4.0

In [82]:
dfmean.mean(0) # média por coluna

A    4.0
B    3.0
dtype: float64

In [83]:
dfmean.mean(1) # média por linha

0    2.0
1    3.0
2    5.5
dtype: float64

In [84]:
df

one     three       two
a  0.251360       NaN  0.175308
b -0.415292 -0.248493 -0.860320
c -0.761420  0.430212 -1.153337
d       NaN  0.664440  0.012675

In [85]:
df.sum(axis =0, skipna=False) # Soma por colunas que não contém NaN

one           NaN
three         NaN
two     -1.825675
dtype: float64

In [86]:
df.sum(axis=1, skipna=True) # soma por linhas mesmo tento NaN

a    0.426668
b   -1.524105
c   -1.484545
d    0.677115
dtype: float64

In [87]:
ts_stand = (df - df.mean()) / df.std()

In [88]:
ts_stand.std() # desvio padrão por colunas

one      1.0
three    1.0
two      1.0
dtype: float64

In [89]:
xs_stand = df.sub(df.mean(1), axis=0).div(df.std(1), axis=0)

In [90]:
xs_stand.std(1) # desvio padrão por linhas

a    1.0
b    1.0
c    1.0
d    1.0
dtype: float64

In [91]:
df

one     three       two
a  0.251360       NaN  0.175308
b -0.415292 -0.248493 -0.860320
c -0.761420  0.430212 -1.153337
d       NaN  0.664440  0.012675

In [92]:
df.cumsum() #soma cumulativa

one     three       two
a  0.251360       NaN  0.175308
b -0.163932 -0.248493 -0.685012
c -0.925352  0.181719 -1.838350
d       NaN  0.846159 -1.825675

In [93]:
np.mean(df['one'])

-0.30845060603013935

In [94]:
np.mean(df['one'].values)

nan

In [95]:
series = pd.Series(np.random.randn(500))
series.head()

0    0.987997
1   -0.825101
2   -0.092302
3    0.897857
4   -0.110665
dtype: float64

In [96]:
series[20:500] = np.nan

In [97]:
series[20:30]

20   NaN
21   NaN
22   NaN
23   NaN
24   NaN
25   NaN
26   NaN
27   NaN
28   NaN
29   NaN
dtype: float64

In [98]:
series[10:20] = 5

In [99]:
series[10:20]

10    5.0
11    5.0
12    5.0
13    5.0
14    5.0
15    5.0
16    5.0
17    5.0
18    5.0
19    5.0
dtype: float64

In [100]:
series.nunique() # conta a quantidade de registros únicos

11

### 8.1 Summarizing data: describe

In [101]:
series = pd.Series(np.random.randn(1000))

In [102]:
series[::2] # exibe os números de 2 em 2

0     -1.060058
2      0.972927
4     -0.608996
6     -2.830267
8      2.098041
10    -1.777735
12     0.357616
14    -0.918722
16     1.641734
18    -1.570673
20     0.481197
22     1.639194
24     0.094984
26     0.285554
28     0.633334
30     1.044160
32     0.336853
34    -0.317407
36     1.322943
38    -1.268101
40    -0.053833
42    -0.277835
44     1.010548
46    -1.148987
48    -0.689626
50     0.280910
52    -0.986170
54    -0.087382
56     1.373957
58     0.402445
         ...   
940   -0.040512
942    0.808006
944   -1.529675
946    0.393088
948    0.091345
950    0.114517
952    0.867244
954    0.816593
956   -0.539103
958    0.504427
960    1.823928
962    0.577399
964    0.506004
966    0.449720
968   -1.222375
970    0.292232
972   -0.526594
974    0.296309
976    0.057044
978    0.220583
980   -0.042723
982    0.280409
984    1.412197
986    0.174534
988    0.290273
990   -0.581499
992   -0.627083
994   -0.624590
996    0.467732
998    0.512414
Length: 500, dtype: floa

In [103]:
series[::3] # exibe os números de 3 em 3

0     -1.060058
3      0.371773
6     -2.830267
9      1.253897
12     0.357616
15     0.372589
18    -1.570673
21     0.878776
24     0.094984
27     0.553276
30     1.044160
33    -1.287202
36     1.322943
39     2.219703
42    -0.277835
45    -0.407257
48    -0.689626
51    -0.562572
54    -0.087382
57     0.608734
60    -0.619465
63     0.232626
66    -1.125096
69    -0.270709
72    -1.442128
75    -0.706227
78     1.123102
81     0.296985
84     2.192190
87    -1.620514
         ...   
912   -1.235668
915    0.061837
918   -0.007366
921   -0.272110
924    0.083296
927    1.014527
930   -0.216566
933    1.219722
936   -0.324932
939   -2.118340
942    0.808006
945   -1.001550
948    0.091345
951    0.508580
954    0.816593
957   -0.052690
960    1.823928
963    1.106883
966    0.449720
969    1.310512
972   -0.526594
975    1.364791
978    0.220583
981   -0.644397
984    1.412197
987    1.577311
990   -0.581499
993   -1.077810
996    0.467732
999    0.786586
Length: 334, dtype: floa

<div style ="background: #ffffe6; padding: 10px">Traz um resumo sumarizado com alguns indicadores:<br><strong>
Contagem (count), Média (mean), Desvio Padrão (std), Valor mínimo (min), Quartil (25%, 50%, 75%), valor máximo (max), mediana (50%)</strong></div>

In [104]:
series.describe() 

count    1000.000000
mean       -0.004202
std         0.999452
min        -3.071732
25%        -0.658694
50%         0.004071
75%         0.637489
max         3.515299
dtype: float64

In [105]:
frame = pd.DataFrame(np.random.randn(1000, 5), columns=['a', 'b', 'c', 'd', 'e'])

In [106]:
frame.iloc[::2] = np.nan # remove os valores dos números pares e troca por NaN

In [107]:
frame.describe()

a           b           c           d           e
count  500.000000  500.000000  500.000000  500.000000  500.000000
mean     0.088884    0.023677    0.081468    0.017444    0.039644
std      1.060057    1.048119    1.027635    1.000264    0.993026
min     -3.929056   -2.951128   -2.848822   -3.175229   -2.820545
25%     -0.627285   -0.687450   -0.602986   -0.600067   -0.637058
50%      0.113974    0.021474    0.101979   -0.010554    0.073089
75%      0.812661    0.666665    0.746037    0.654764    0.717998
max      3.038942    3.767414    3.964377    2.881870    3.784328

In [108]:
series

0     -1.060058
1      0.289065
2      0.972927
3      0.371773
4     -0.608996
5     -0.080668
6     -2.830267
7     -0.279078
8      2.098041
9      1.253897
10    -1.777735
11     1.181731
12     0.357616
13    -0.534894
14    -0.918722
15     0.372589
16     1.641734
17    -0.429145
18    -1.570673
19     0.406026
20     0.481197
21     0.878776
22     1.639194
23    -0.356308
24     0.094984
25    -0.571126
26     0.285554
27     0.553276
28     0.633334
29    -0.062115
         ...   
970    0.292232
971    0.087440
972   -0.526594
973   -0.505307
974    0.296309
975    1.364791
976    0.057044
977   -0.131356
978    0.220583
979   -0.857296
980   -0.042723
981   -0.644397
982    0.280409
983   -0.616119
984    1.412197
985   -0.640317
986    0.174534
987    1.577311
988    0.290273
989   -0.083941
990   -0.581499
991    0.982943
992   -0.627083
993   -1.077810
994   -0.624590
995   -0.190990
996    0.467732
997    0.014475
998    0.512414
999    0.786586
Length: 1000, dtype: flo

In [109]:
series.describe()

count    1000.000000
mean       -0.004202
std         0.999452
min        -3.071732
25%        -0.658694
50%         0.004071
75%         0.637489
max         3.515299
dtype: float64

In [110]:
# Definir mais porcentagens para exibição
series.describe(percentiles=[.05, .25, .75, .95])

count    1000.000000
mean       -0.004202
std         0.999452
min        -3.071732
5%         -1.621516
25%        -0.658694
50%         0.004071
75%         0.637489
95%         1.577820
max         3.515299
dtype: float64

In [111]:
# Descrição de dados não numericos
s = pd.Series(['a', 'a', 'b', 'b', 'a', 'a', np.nan, 'c', 'd', 'a'])

In [112]:
s.describe()

count     9
unique    4
top       a
freq      5
dtype: object

In [113]:
frame = pd.DataFrame({
    'a': ['Yes', 'Yes', 'No', 'No'],
    'b': range(4)
})
frame

a  b
0  Yes  0
1  Yes  1
2   No  2
3   No  3

In [114]:
# Em dados mistos, o describe vai apenas descrever os dados que forem numericos e 
# ocultar os dados não numericos
frame.describe()

b
count  4.000000
mean   1.500000
std    1.290994
min    0.000000
25%    0.750000
50%    1.500000
75%    2.250000
max    3.000000

In [115]:
# Este comportamento pode ser controlado através do parêmetro include/exclude
frame.describe(include='all')

a         b
count     4  4.000000
unique    2       NaN
top      No       NaN
freq      2       NaN
mean    NaN  1.500000
std     NaN  1.290994
min     NaN  0.000000
25%     NaN  0.750000
50%     NaN  1.500000
75%     NaN  2.250000
max     NaN  3.000000

In [116]:
# Ou retringir a um tipo
frame.describe(include='object')

a
count    4
unique   2
top     No
freq     2

In [117]:
# Ou selecionar mais de um tipo
frame.describe(include=['object', 'number'])

a         b
count     4  4.000000
unique    2       NaN
top      No       NaN
freq      2       NaN
mean    NaN  1.500000
std     NaN  1.290994
min     NaN  0.000000
25%     NaN  0.750000
50%     NaN  1.500000
75%     NaN  2.250000
max     NaN  3.000000

### 8.2 Index of Min/Max Values

In [118]:
s1 = pd.Series(np.random.randn(5)) ;s1

0    0.638613
1    0.331621
2   -1.005634
3   -0.229736
4   -0.133536
dtype: float64

In [119]:
s1.idxmin(), s1.idxmax()

(2, 0)

In [120]:
df1 = pd.DataFrame(np.random.randn(5, 3), columns=['A', 'B', 'C']); df1

A         B         C
0  0.309127 -0.960880  1.220884
1 -0.022794  0.434471  0.598121
2 -0.579923 -0.245726 -0.782765
3  0.371661 -0.682903 -0.673766
4  0.316059  0.073945 -0.857265

In [121]:
# Seleciona o indice que contem o menor valor de cada coluna:
df1.idxmin(axis=0)

A    2
B    0
C    4
dtype: int64

In [122]:
# Mostra em qual coluna está o indice do menor para o maior com relação as valores.v
df1.idxmin(axis=1)

0    B
1    A
2    C
3    B
4    C
dtype: object

In [123]:
# Quando tem mais de um valor mínimo, retornará o primeiro indice localizado
df3 = pd.DataFrame([2, 1, 1, 3, np.nan], columns=['A'], index=list('edcba'))
df3

A
e  2.0
d  1.0
c  1.0
b  3.0
a  NaN

In [124]:
df3['A'].idxmin()

'd'

#### Note: idxmin and idxmax are called argmin and argmax in NumPy.

### 8.3 Value counts (histogramming)/ Mode

In [125]:
data = np.random.randint(0, 7, size= 50); data

array([1, 6, 3, 0, 5, 1, 4, 6, 0, 1, 3, 6, 4, 6, 6, 1, 5, 4, 2, 3, 6, 3, 4,
       3, 4, 2, 6, 6, 5, 1, 3, 3, 1, 6, 4, 0, 0, 5, 2, 2, 5, 1, 3, 2, 0, 2,
       0, 1, 0, 2])

In [126]:
s = pd.Series(data)

In [127]:
s.value_counts()

6    9
3    8
1    8
2    7
0    7
4    6
5    5
dtype: int64

In [128]:
# Dá par utilizar direto do metodo value_counts do Pandas. Obterá o mesmo resultado
pd.value_counts(data)

6    9
3    8
1    8
2    7
0    7
4    6
5    5
dtype: int64

In [129]:
# Você pode selecionar os registros de maiores ocorrências em uma Serie ou DataFrame
s5 = pd.Series([1, 1, 3, 3, 3, 5, 5, 7, 7, 7])

In [130]:
s5.mode()

0    3
1    7
dtype: int64

In [131]:
s5 = pd.Series([1, 1, 3, 3, 3, 5, 5, 7, 7, 7, 7])

In [132]:
s5.mode()

0    7
dtype: int64

In [133]:
df5 = pd.DataFrame({
    'A': np.random.randint(0, 7, size=50),
    'B': np.random.randint(-10, 15, size=50)
})

In [134]:
df5.mode()

A   B
0  6.0  -3
1  NaN   2
2  NaN   7
3  NaN  10

### 8.4 Discretization and quantiling

In [135]:
arr = np.random.randn(20); arr

array([ 0.29115694,  0.58676463,  0.34110101, -0.20752017,  0.6918525 ,
        0.09206157, -0.97130955, -0.64626257,  3.05797944,  0.34486316,
        1.08964843,  0.48405889, -0.41987016, -0.28482994, -1.01087605,
        0.67348848,  0.09462929,  0.10252866,  0.58497615, -0.0888993 ])

In [136]:
factor = pd.cut(arr, 4) # curta os dados em 4 partes
factor

[(0.00634, 1.024], (0.00634, 1.024], (0.00634, 1.024], (-1.015, 0.00634], (0.00634, 1.024], ..., (0.00634, 1.024], (0.00634, 1.024], (0.00634, 1.024], (0.00634, 1.024], (-1.015, 0.00634]]
Length: 20
Categories (4, interval[float64]): [(-1.015, 0.00634] < (0.00634, 1.024] < (1.024, 2.041] < (2.041, 3.058]]

In [137]:
factor = pd.cut(arr, [-5, -1, 0, 1, 5])
factor

[(0, 1], (0, 1], (0, 1], (-1, 0], (0, 1], ..., (0, 1], (0, 1], (0, 1], (0, 1], (-1, 0]]
Length: 20
Categories (4, interval[int64]): [(-5, -1] < (-1, 0] < (0, 1] < (1, 5]]

In [138]:
arr = np.random.randn(30); arr

array([-0.05515993,  0.64820328,  0.85493647, -0.59029895,  0.00652942,
        0.67491222, -1.22300685, -0.60838893, -0.57767205, -1.35331571,
       -1.30200625,  0.53753421, -1.20756566, -0.579001  ,  0.53369462,
       -0.02789188,  1.0497522 ,  0.74807216, -0.82692534,  1.57619656,
       -0.50696434,  0.3082039 , -2.11345242,  0.70627974, -0.20828736,
        1.46431156, -0.33084914, -0.24891262, -0.24340808,  0.40992748])

In [139]:
factor = pd.qcut(arr, [0, .25, .5, .75, 1])
factor

[(-0.132, 0.621], (0.621, 1.576], (0.621, 1.576], (-2.114, -0.587], (-0.132, 0.621], ..., (0.621, 1.576], (-0.587, -0.132], (-0.587, -0.132], (-0.587, -0.132], (-0.132, 0.621]]
Length: 30
Categories (4, interval[float64]): [(-2.114, -0.587] < (-0.587, -0.132] < (-0.132, 0.621] < (0.621, 1.576]]

In [140]:
pd.value_counts(factor)

(0.621, 1.576]      8
(-2.114, -0.587]    8
(-0.132, 0.621]     7
(-0.587, -0.132]    7
dtype: int64

In [141]:
# infinite values
arr = np.random.randn(20); arr

array([ 0.10248571,  2.10868295,  0.03561027,  1.52475947, -0.30873689,
       -0.09318297,  0.89732786, -1.69674925, -0.78772828, -0.89112824,
       -1.63614278, -1.30260542, -1.92160192,  2.13624457, -1.07960835,
       -0.17231922, -0.5140375 ,  1.34027199, -1.32370227,  1.45327613])

In [142]:
factor = pd.cut(arr, [-np.inf, 0, np.inf])
factor

[(0.0, inf], (0.0, inf], (0.0, inf], (0.0, inf], (-inf, 0.0], ..., (-inf, 0.0], (-inf, 0.0], (0.0, inf], (-inf, 0.0], (0.0, inf]]
Length: 20
Categories (2, interval[float64]): [(-inf, 0.0] < (0.0, inf]]

# 9 Function application

### 9.1 Tablewise Function Application

In [143]:
import statsmodels.formula.api as sm

In [144]:
bb = pd.read_csv('../data/pydata/baseball.csv', index_col='id')

In [145]:
# f, g, and h are functions taking and returning ``DataFrames``
(bb.query('h > 0')
     .assign(ln_h = lambda df: np.log(df.h))
     .pipe((sm.poisson, 'data'), 'hr ~ ln_h + year + g + C(lg)')
     .fit()
     .summary2() # na documentação oficial está .summary() mas está aparecendo uma mensagem de erro
)

Optimization terminated successfully.
         Current function value: 2.116284
         Iterations 24


<class 'statsmodels.iolib.summary2.Summary'>
"""
                         Results: Poisson
===================================================================
Model:                Poisson           No. Iterations:    24.0000 
Dependent Variable:   hr                Pseudo R-squared:  0.688   
Date:                 2018-04-20 14:08  AIC:               297.8147
No. Observations:     68                BIC:               308.9122
Df Model:             4                 Log-Likelihood:    -143.91 
Df Residuals:         63                LL-Null:           -460.91 
Converged:            1.0000            Scale:             1.0000  
-------------------------------------------------------------------
              Coef.    Std.Err.    z    P>|z|    [0.025     0.975] 
-------------------------------------------------------------------
Intercept   -1267.3636 457.8674 -2.7680 0.0056 -2164.7672 -369.9601
C(lg)[T.NL]    -0.2057   0.1006 -2.0438 0.0410    -0.4029   -0.0084
ln_h            0.9280   0.1907  4.8655 0.0000     0.5542    1.3018
year            0.6301   0.2282  2.7617 0.0058     0.1829    1.0772
g               0.0099   0.0036  2.7541 0.0059     0.0029    0.0170
===================================================================

"""

### 9.2 Row or Column-wise Function Application

In [146]:
df.apply(np.mean)

one     -0.308451
three    0.282053
two     -0.456419
dtype: float64

In [147]:
df.apply(np.mean, axis=1)

a    0.213334
b   -0.508035
c   -0.494848
d    0.338557
dtype: float64

In [148]:
df.apply(lambda x: x.max() - x.min())

one      1.012780
three    0.912933
two      1.328645
dtype: float64

In [149]:
df.apply(np.cumsum)

one     three       two
a  0.251360       NaN  0.175308
b -0.163932 -0.248493 -0.685012
c -0.925352  0.181719 -1.838350
d       NaN  0.846159 -1.825675

In [150]:
df.apply(np.exp)

one     three       two
a  1.285773       NaN  1.191613
b  0.660148  0.779976  0.423027
c  0.467003  1.537583  0.315582
d       NaN  1.943403  1.012755

In [151]:
# dá para chamar o método como string
df.apply('mean')

one     -0.308451
three    0.282053
two     -0.456419
dtype: float64

In [152]:
df.apply('mean', axis=1)

a    0.213334
b   -0.508035
c   -0.494848
d    0.338557
dtype: float64

In [153]:
tsdf = pd.DataFrame(np.random.randn(1000, 3), columns=['A', 'B', 'C'], index=pd.date_range('1/1/2000', periods=1000))

In [154]:
tsdf.head()

A         B         C
2000-01-01  0.312326  0.580970  1.648172
2000-01-02  0.333095 -0.333629  0.497820
2000-01-03 -0.956783  1.571086  0.024643
2000-01-04 -0.370372  0.844068 -0.109218
2000-01-05  0.843121  0.927606  0.669331

In [155]:
tsdf.apply(lambda x: x.idxmax())

A   2001-03-18
B   2000-05-23
C   2000-09-12
dtype: datetime64[ns]

In [156]:
def substract_and_divide(x, sub, divide=1):
    return (x - sub) / divide

In [157]:
df.apply(substract_and_divide, args=(5,), divide=3)

one     three       two
a -1.582880       NaN -1.608231
b -1.805097 -1.749498 -1.953440
c -1.920473 -1.523263 -2.051112
d       NaN -1.445187 -1.662442

In [158]:
tsdf

A         B         C
2000-01-01  0.312326  0.580970  1.648172
2000-01-02  0.333095 -0.333629  0.497820
2000-01-03 -0.956783  1.571086  0.024643
2000-01-04 -0.370372  0.844068 -0.109218
2000-01-05  0.843121  0.927606  0.669331
2000-01-06 -0.798024 -1.821860  0.930142
2000-01-07 -0.282643 -2.584808  0.298548
2000-01-08 -0.244291 -0.690702  0.000866
2000-01-09 -2.227868  0.283576 -0.047918
2000-01-10  1.630751 -1.890195  2.794424
2000-01-11  0.015278 -1.063339  0.541784
2000-01-12 -0.106249  1.101253 -0.471768
2000-01-13  0.436039  0.249927  0.107755
2000-01-14 -1.305195 -1.891265 -0.618396
2000-01-15  1.148919  0.151036 -0.798700
2000-01-16 -0.233523  1.456068 -0.007959
2000-01-17  0.260754 -2.402288 -0.709397
2000-01-18 -0.931870  0.667657 -0.808418
2000-01-19 -0.679368 -2.398131 -0.762001
2000-01-20  0.668290 -0.235552  0.242292
2000-01-21 -0.913396  1.267218  0.284446
2000-01-22  1.395036 -0.492756 -1.222282
2000-01-23  0.604861 -0.336387 -0.431209
2000-01-24  0.682265  0.414226  1.895319
2000-01-25 -0.290309  0.672889 -0.292995
2000-01-26  1.405207 -0.150240 -0.407311
2000-01-27 -0.932510 -0.262310  1.444446
2000-01-28  0.293114  0.275461 -1.027848
2000-01-29 -0.500698  2.706221  0.771587
2000-01-30 -1.265616 -0.018428 -1.486651
...              ...       ...       ...
2002-08-28  1.070237 -0.727205 -0.754674
2002-08-29  0.765571  0.316630  0.165800
2002-08-30  1.014623  1.010821  0.914366
2002-08-31  0.679189 -2.937790 -0.698591
2002-09-01 -1.546291 -1.086614 -0.675522
2002-09-02  0.336487 -1.122504  0.199502
2002-09-03  0.953189  0.733480 -0.174221
2002-09-04 -0.445421  0.286353 -2.133166
2002-09-05 -1.254885  1.532890 -0.736864
2002-09-06 -0.159324 -1.215089 -0.166580
2002-09-07  0.038007 -0.695336 -0.441466
2002-09-08 -1.285363 -1.118365 -0.325691
2002-09-09 -1.005892 -0.875173 -0.158457
2002-09-10 -0.766341  0.072857  0.983907
2002-09-11  1.083662 -0.208997 -0.299422
2002-09-12  0.228528  1.524078  0.265258
2002-09-13  0.263614 -0.613881 -0.963654
2002-09-14 -0.429883 -0.392466  0.133077
2002-09-15 -0.254930  1.182034 -0.776376
2002-09-16  0.827510  0.539297  0.613245
2002-09-17 -0.289173 -2.145319  0.670230
2002-09-18  0.248961 -0.943695  1.702288
2002-09-19  1.668096 -0.287219  0.879450
2002-09-20  1.698025  1.092087  0.514951
2002-09-21 -0.247957  1.585737  0.309012
2002-09-22 -0.428685 -0.260929  0.764834
2002-09-23  0.242623  0.398633  0.226450
2002-09-24  1.591676 -1.226811 -0.038376
2002-09-25  0.267770  1.024287 -1.359254
2002-09-26  0.610215 -0.440142  0.078418

[1000 rows x 3 columns]

In [159]:
tsdf.apply(pd.Series.interpolate)

A         B         C
2000-01-01  0.312326  0.580970  1.648172
2000-01-02  0.333095 -0.333629  0.497820
2000-01-03 -0.956783  1.571086  0.024643
2000-01-04 -0.370372  0.844068 -0.109218
2000-01-05  0.843121  0.927606  0.669331
2000-01-06 -0.798024 -1.821860  0.930142
2000-01-07 -0.282643 -2.584808  0.298548
2000-01-08 -0.244291 -0.690702  0.000866
2000-01-09 -2.227868  0.283576 -0.047918
2000-01-10  1.630751 -1.890195  2.794424
2000-01-11  0.015278 -1.063339  0.541784
2000-01-12 -0.106249  1.101253 -0.471768
2000-01-13  0.436039  0.249927  0.107755
2000-01-14 -1.305195 -1.891265 -0.618396
2000-01-15  1.148919  0.151036 -0.798700
2000-01-16 -0.233523  1.456068 -0.007959
2000-01-17  0.260754 -2.402288 -0.709397
2000-01-18 -0.931870  0.667657 -0.808418
2000-01-19 -0.679368 -2.398131 -0.762001
2000-01-20  0.668290 -0.235552  0.242292
2000-01-21 -0.913396  1.267218  0.284446
2000-01-22  1.395036 -0.492756 -1.222282
2000-01-23  0.604861 -0.336387 -0.431209
2000-01-24  0.682265  0.414226  1.895319
2000-01-25 -0.290309  0.672889 -0.292995
2000-01-26  1.405207 -0.150240 -0.407311
2000-01-27 -0.932510 -0.262310  1.444446
2000-01-28  0.293114  0.275461 -1.027848
2000-01-29 -0.500698  2.706221  0.771587
2000-01-30 -1.265616 -0.018428 -1.486651
...              ...       ...       ...
2002-08-28  1.070237 -0.727205 -0.754674
2002-08-29  0.765571  0.316630  0.165800
2002-08-30  1.014623  1.010821  0.914366
2002-08-31  0.679189 -2.937790 -0.698591
2002-09-01 -1.546291 -1.086614 -0.675522
2002-09-02  0.336487 -1.122504  0.199502
2002-09-03  0.953189  0.733480 -0.174221
2002-09-04 -0.445421  0.286353 -2.133166
2002-09-05 -1.254885  1.532890 -0.736864
2002-09-06 -0.159324 -1.215089 -0.166580
2002-09-07  0.038007 -0.695336 -0.441466
2002-09-08 -1.285363 -1.118365 -0.325691
2002-09-09 -1.005892 -0.875173 -0.158457
2002-09-10 -0.766341  0.072857  0.983907
2002-09-11  1.083662 -0.208997 -0.299422
2002-09-12  0.228528  1.524078  0.265258
2002-09-13  0.263614 -0.613881 -0.963654
2002-09-14 -0.429883 -0.392466  0.133077
2002-09-15 -0.254930  1.182034 -0.776376
2002-09-16  0.827510  0.539297  0.613245
2002-09-17 -0.289173 -2.145319  0.670230
2002-09-18  0.248961 -0.943695  1.702288
2002-09-19  1.668096 -0.287219  0.879450
2002-09-20  1.698025  1.092087  0.514951
2002-09-21 -0.247957  1.585737  0.309012
2002-09-22 -0.428685 -0.260929  0.764834
2002-09-23  0.242623  0.398633  0.226450
2002-09-24  1.591676 -1.226811 -0.038376
2002-09-25  0.267770  1.024287 -1.359254
2002-09-26  0.610215 -0.440142  0.078418

[1000 rows x 3 columns]

### 9.3 Aggregation API

In [160]:
tsdf = pd.DataFrame(np.random.randn(10, 3), columns=['A', 'B', 'C'],
                   index=pd.date_range('1/1/2000', periods=10))

In [161]:
tsdf

A         B         C
2000-01-01  0.614038 -0.011056  0.434864
2000-01-02 -0.018007  0.717412 -0.693321
2000-01-03 -0.201301  1.421533 -0.589413
2000-01-04  0.295115  0.432911 -0.105158
2000-01-05 -0.473430  1.103269 -0.023410
2000-01-06 -0.579984 -1.965700 -0.029392
2000-01-07 -2.164249  0.719011  0.144846
2000-01-08  0.765105 -1.142685 -0.247540
2000-01-09  0.670142 -0.536984  0.502197
2000-01-10  0.029381 -0.880616  0.842408

In [162]:
tsdf.iloc[3:7] = np.nan

In [163]:
tsdf

A         B         C
2000-01-01  0.614038 -0.011056  0.434864
2000-01-02 -0.018007  0.717412 -0.693321
2000-01-03 -0.201301  1.421533 -0.589413
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08  0.765105 -1.142685 -0.247540
2000-01-09  0.670142 -0.536984  0.502197
2000-01-10  0.029381 -0.880616  0.842408

In [164]:
tsdf.agg(np.sum) # similar ao apply

A    1.859357
B   -0.432397
C    0.249196
dtype: float64

In [165]:
tsdf.agg('sum')

A    1.859357
B   -0.432397
C    0.249196
dtype: float64

In [166]:
tsdf.sum()

A    1.859357
B   -0.432397
C    0.249196
dtype: float64

In [167]:
tsdf.A

2000-01-01    0.614038
2000-01-02   -0.018007
2000-01-03   -0.201301
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
2000-01-08    0.765105
2000-01-09    0.670142
2000-01-10    0.029381
Freq: D, Name: A, dtype: float64

In [168]:
tsdf.A.agg('sum')

1.8593573281606357

#### 9.3.1 Aggregation with multiple functions

In [169]:
tsdf.agg(['sum'])

A         B         C
sum  1.859357 -0.432397  0.249196

In [170]:
tsdf.agg(['sum', 'mean'])

A         B         C
sum   1.859357 -0.432397  0.249196
mean  0.309893 -0.072066  0.041533

In [171]:
tsdf.A.agg(['sum', 'mean'])

sum     1.859357
mean    0.309893
Name: A, dtype: float64

In [172]:
tsdf.A.agg(['sum', lambda x: x.mean()])

sum         1.859357
<lambda>    0.309893
Name: A, dtype: float64

In [173]:
def my_mean(x):
    return x.mean()

In [174]:
tsdf.A.agg(['sum', my_mean])

sum        1.859357
my_mean    0.309893
Name: A, dtype: float64

#### 9.3.2 Aggregating with a dict

In [175]:
tsdf.agg({
    'A': 'mean',
    'B': 'sum'
})

A    0.309893
B   -0.432397
dtype: float64

In [176]:
tsdf.agg({
    'A': ['mean', 'min'],
    'B': 'sum'
})

A         B
mean  0.309893       NaN
min  -0.201301       NaN
sum        NaN -0.432397

#### 9.3.3 Mixed Dtypes

In [177]:
mdf = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [1., 2., 3.],
    'C': ['foo', 'bar', 'baz'],
    'D': pd.date_range('20130101', periods=3)
})

In [178]:
mdf.dtypes

A             int64
B           float64
C            object
D    datetime64[ns]
dtype: object

In [179]:
mdf.agg(['min', 'sum'])

A    B          C          D
min  1  1.0        bar 2013-01-01
sum  6  6.0  foobarbaz        NaT

#### 9.3.4 Custom describe (Muito útil)

In [180]:
from functools import partial

In [181]:
q_25 = partial(pd.Series.quantile, q=0.25)

In [182]:
q_25.__name__ = '25%'

In [183]:
q_75 = partial(pd.Series.quantile, q=0.75)

In [184]:
q_75.__name__ = '75%'

In [185]:
tsdf.agg(['count', 'mean', 'std', 'min', q_25, 'median', q_75, 'max'])

A         B         C
count   6.000000  6.000000  6.000000
mean    0.309893 -0.072066  0.041533
std     0.418814  0.987316  0.637179
min    -0.201301 -1.142685 -0.693321
25%    -0.006160 -0.794708 -0.503944
median  0.321709 -0.274020  0.093662
75%     0.656116  0.535295  0.485364
max     0.765105  1.421533  0.842408

### 9.4 Transform API

In [186]:
tsdf = pd.DataFrame(np.random.randn(10, 3), columns=['A', 'B', 'C'],
                   index=pd.date_range('1/1/2000', periods=10))
tsdf

A         B         C
2000-01-01  0.390926 -0.850702  0.390932
2000-01-02  1.787179  0.004634 -0.112415
2000-01-03  2.175914  0.143761  1.382045
2000-01-04  2.157990 -1.395819  0.499933
2000-01-05 -1.437348 -0.166072  2.109205
2000-01-06 -0.443917  0.195218 -1.520192
2000-01-07 -0.517687 -1.809674 -0.508571
2000-01-08  1.565380  0.808940  0.701242
2000-01-09  0.113363  0.286419  0.211047
2000-01-10 -0.393385 -0.047356  0.376921

In [187]:
tsdf.iloc[3:7] = np.nan; tsdf

A         B         C
2000-01-01  0.390926 -0.850702  0.390932
2000-01-02  1.787179  0.004634 -0.112415
2000-01-03  2.175914  0.143761  1.382045
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08  1.565380  0.808940  0.701242
2000-01-09  0.113363  0.286419  0.211047
2000-01-10 -0.393385 -0.047356  0.376921

In [188]:
tsdf.transform(np.abs) # transdorma em valor absoluto

A         B         C
2000-01-01  0.390926  0.850702  0.390932
2000-01-02  1.787179  0.004634  0.112415
2000-01-03  2.175914  0.143761  1.382045
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08  1.565380  0.808940  0.701242
2000-01-09  0.113363  0.286419  0.211047
2000-01-10  0.393385  0.047356  0.376921

In [189]:
tsdf.transform('abs')

A         B         C
2000-01-01  0.390926  0.850702  0.390932
2000-01-02  1.787179  0.004634  0.112415
2000-01-03  2.175914  0.143761  1.382045
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08  1.565380  0.808940  0.701242
2000-01-09  0.113363  0.286419  0.211047
2000-01-10  0.393385  0.047356  0.376921

In [190]:
tsdf.transform(lambda x: x.abs())

A         B         C
2000-01-01  0.390926  0.850702  0.390932
2000-01-02  1.787179  0.004634  0.112415
2000-01-03  2.175914  0.143761  1.382045
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08  1.565380  0.808940  0.701242
2000-01-09  0.113363  0.286419  0.211047
2000-01-10  0.393385  0.047356  0.376921

In [191]:
# Dá para utilziar o metodo direto do  numpy similar aos anteriores
np.abs(tsdf)

A         B         C
2000-01-01  0.390926  0.850702  0.390932
2000-01-02  1.787179  0.004634  0.112415
2000-01-03  2.175914  0.143761  1.382045
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08  1.565380  0.808940  0.701242
2000-01-09  0.113363  0.286419  0.211047
2000-01-10  0.393385  0.047356  0.376921

In [192]:
tsdf.A.transform(np.abs)

2000-01-01    0.390926
2000-01-02    1.787179
2000-01-03    2.175914
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
2000-01-08    1.565380
2000-01-09    0.113363
2000-01-10    0.393385
Freq: D, Name: A, dtype: float64

#### 9.4.1 Transform with multiple functions

In [193]:
tsdf.transform([np.abs, lambda x: x + 1])

A                   B                   C          
            absolute  <lambda>  absolute  <lambda>  absolute  <lambda>
2000-01-01  0.390926  1.390926  0.850702  0.149298  0.390932  1.390932
2000-01-02  1.787179  2.787179  0.004634  1.004634  0.112415  0.887585
2000-01-03  2.175914  3.175914  0.143761  1.143761  1.382045  2.382045
2000-01-04       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-08  1.565380  2.565380  0.808940  1.808940  0.701242  1.701242
2000-01-09  0.113363  1.113363  0.286419  1.286419  0.211047  1.211047
2000-01-10  0.393385  0.606615  0.047356  0.952644  0.376921  1.376921

In [194]:
tsdf.A.transform([np.abs, lambda x: x +1])

absolute  <lambda>
2000-01-01  0.390926  1.390926
2000-01-02  1.787179  2.787179
2000-01-03  2.175914  3.175914
2000-01-04       NaN       NaN
2000-01-05       NaN       NaN
2000-01-06       NaN       NaN
2000-01-07       NaN       NaN
2000-01-08  1.565380  2.565380
2000-01-09  0.113363  1.113363
2000-01-10  0.393385  0.606615

#### 9.4.2 Transforming with a dict

In [195]:
tsdf.transform({
    'A': np.abs,
    'B': lambda x: x+1
})

A         B
2000-01-01  0.390926  0.149298
2000-01-02  1.787179  1.004634
2000-01-03  2.175914  1.143761
2000-01-04       NaN       NaN
2000-01-05       NaN       NaN
2000-01-06       NaN       NaN
2000-01-07       NaN       NaN
2000-01-08  1.565380  1.808940
2000-01-09  0.113363  1.286419
2000-01-10  0.393385  0.952644

In [196]:
tsdf.transform({
    'A': np.abs,
    'B': [lambda x: x+1, np.sqrt] # na documentação estava 'sqrt' e deu um erro
})

A         B          
            absolute  <lambda>      sqrt
2000-01-01  0.390926  0.149298       NaN
2000-01-02  1.787179  1.004634  0.068074
2000-01-03  2.175914  1.143761  0.379158
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08  1.565380  1.808940  0.899411
2000-01-09  0.113363  1.286419  0.535182
2000-01-10  0.393385  0.952644       NaN

#### 9.4.3 Applying Elementwise Functions

In [197]:
df

one     three       two
a  0.251360       NaN  0.175308
b -0.415292 -0.248493 -0.860320
c -0.761420  0.430212 -1.153337
d       NaN  0.664440  0.012675

In [198]:
f = lambda x: len(str(x))

In [199]:
df['one'].map(f)

a    18
b    19
c    19
d     3
Name: one, dtype: int64

In [200]:
df.applymap(f)

one  three  two
a   18      3   19
b   19     20   19
c   19     18   19
d    3     18   20

In [201]:
s = pd.Series(['six', 'seven', 'six', 'seven', 'six'],
             index=['a', 'b', 'c', 'd', 'e'])
s

a      six
b    seven
c      six
d    seven
e      six
dtype: object

In [202]:
t = pd.Series({
    'six': 6.,
    'seven': 7.
})
t

seven    7.0
six      6.0
dtype: float64

In [203]:
s.map(t)

a    6.0
b    7.0
c    6.0
d    7.0
e    6.0
dtype: float64

#### 9.4.4 Applying with a Panel

In [204]:
import pandas.util.testing as tm

In [205]:
panel = tm.makePanel(5)

In [206]:
panel

<class 'pandas.core.panel.Panel'>
Dimensions: 3 (items) x 5 (major_axis) x 4 (minor_axis)
Items axis: ItemA to ItemC
Major_axis axis: 2000-01-03 00:00:00 to 2000-01-07 00:00:00
Minor_axis axis: A to D

In [207]:
panel['ItemA']

A         B         C         D
2000-01-03 -0.214591 -1.046827  2.175638  0.205938
2000-01-04 -0.632806  0.315627 -1.429304 -0.149261
2000-01-05 -1.823236 -0.881438  0.055200  0.051204
2000-01-06  0.136848  0.272857  0.619018  0.361853
2000-01-07 -1.252223 -0.544329  1.960980 -0.788473

In [208]:
result = panel.apply(lambda x: x*2, axis='items')
result

<class 'pandas.core.panel.Panel'>
Dimensions: 3 (items) x 5 (major_axis) x 4 (minor_axis)
Items axis: ItemA to ItemC
Major_axis axis: 2000-01-03 00:00:00 to 2000-01-07 00:00:00
Minor_axis axis: A to D

In [209]:
result['ItemA']

A         B         C         D
2000-01-03 -0.429181 -2.093655  4.351277  0.411875
2000-01-04 -1.265612  0.631255 -2.858608 -0.298523
2000-01-05 -3.646472 -1.762876  0.110399  0.102408
2000-01-06  0.273697  0.545715  1.238035  0.723706
2000-01-07 -2.504446 -1.088658  3.921961 -1.576946

In [210]:
panel.apply(lambda x: x.dtype, axis='items')

A        B        C        D
2000-01-03  float64  float64  float64  float64
2000-01-04  float64  float64  float64  float64
2000-01-05  float64  float64  float64  float64
2000-01-06  float64  float64  float64  float64
2000-01-07  float64  float64  float64  float64

In [211]:
panel.apply(lambda x: x.sum(), axis='major_axis')

ItemA     ItemB     ItemC
A -3.786007  1.492095  2.273851
B -1.884110 -0.119683  3.357636
C  3.381532 -1.573138  0.338979
D -0.318740  0.546667 -2.878733

In [212]:
panel.sum('major_axis') # resultado similar ao anterior

ItemA     ItemB     ItemC
A -3.786007  1.492095  2.273851
B -1.884110 -0.119683  3.357636
C  3.381532 -1.573138  0.338979
D -0.318740  0.546667 -2.878733

In [213]:
result = panel.apply(
    lambda x: (x-x.mean())/x.std(),
    axis='major_axis'
)
result

<class 'pandas.core.panel.Panel'>
Dimensions: 3 (items) x 5 (major_axis) x 4 (minor_axis)
Items axis: ItemA to ItemC
Major_axis axis: 2000-01-03 00:00:00 to 2000-01-07 00:00:00
Minor_axis axis: A to D

In [214]:
result['ItemA']

A         B         C         D
2000-01-03  0.687634 -1.048558  1.015415  0.603179
2000-01-04  0.157643  1.083682 -1.426015 -0.191260
2000-01-05 -1.350953 -0.789723 -0.420642  0.257101
2000-01-06  1.133003  1.016747 -0.038798  0.951899
2000-01-07 -0.627326 -0.262148  0.870039 -1.620920

In [215]:
f = lambda x: ((x.T-x.mean(1))/x.std(1)).T

In [216]:
result = panel.apply(f, axis=['items', 'major_axis']); result

<class 'pandas.core.panel.Panel'>
Dimensions: 4 (items) x 5 (major_axis) x 3 (minor_axis)
Items axis: A to D
Major_axis axis: 2000-01-03 00:00:00 to 2000-01-07 00:00:00
Minor_axis axis: ItemA to ItemC

In [217]:
result.loc[:,:,'ItemA']

A         B         C         D
2000-01-03 -0.800901 -0.800377  1.140797  0.703060
2000-01-04 -0.581927 -0.790907 -1.151769 -0.008633
2000-01-05 -1.154531 -0.583574  0.437617  0.272123
2000-01-06  0.740759 -0.971595  0.330027  0.781636
2000-01-07 -1.127530 -0.175440  1.046382 -0.903451

In [218]:
# Resultado equivalonte
result = pd.Panel(dict([
    (ax, f(panel.loc[:,:,ax])) 
    for ax in panel.minor_axis
]))
result

<class 'pandas.core.panel.Panel'>
Dimensions: 4 (items) x 5 (major_axis) x 3 (minor_axis)
Items axis: A to D
Major_axis axis: 2000-01-03 00:00:00 to 2000-01-07 00:00:00
Minor_axis axis: ItemA to ItemC

In [219]:
result.loc[:,:,'ItemA']

A         B         C         D
2000-01-03 -0.800901 -0.800377  1.140797  0.703060
2000-01-04 -0.581927 -0.790907 -1.151769 -0.008633
2000-01-05 -1.154531 -0.583574  0.437617  0.272123
2000-01-06  0.740759 -0.971595  0.330027  0.781636
2000-01-07 -1.127530 -0.175440  1.046382 -0.903451

# 10 Reindexing and altering labels

In [220]:
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
s

a    0.713821
b    0.446430
c   -1.959724
d   -0.327636
e    0.385377
dtype: float64

In [221]:
s.reindex(['e', 'b', 'f', 'd'])

e    0.385377
b    0.446430
f         NaN
d   -0.327636
dtype: float64

In [222]:
df

one     three       two
a  0.251360       NaN  0.175308
b -0.415292 -0.248493 -0.860320
c -0.761420  0.430212 -1.153337
d       NaN  0.664440  0.012675

In [223]:
df.reindex(index=['c', 'f', 'b'], columns=['three', 'two', 'one'])

three       two       one
c  0.430212 -1.153337 -0.761420
f       NaN       NaN       NaN
b -0.248493 -0.860320 -0.415292

In [224]:
df.reindex(['c', 'f', 'b'], axis='index')

one     three       two
c -0.761420  0.430212 -1.153337
f       NaN       NaN       NaN
b -0.415292 -0.248493 -0.860320

In [225]:
rs = s.reindex(df.index); rs

a    0.713821
b    0.446430
c   -1.959724
d   -0.327636
dtype: float64

In [226]:
rs.index is df.index

True

In [227]:
df.reindex(['c', 'f', 'b'], axis='index')

one     three       two
c -0.761420  0.430212 -1.153337
f       NaN       NaN       NaN
b -0.415292 -0.248493 -0.860320

In [228]:
df.reindex(['three', 'two', 'one'], axis='columns')

three       two       one
a       NaN  0.175308  0.251360
b -0.248493 -0.860320 -0.415292
c  0.430212 -1.153337 -0.761420
d  0.664440  0.012675       NaN

### 10.1 Aligning objects with each other with align

In [229]:
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])

In [230]:
s

a    0.874135
b    0.681662
c    1.206386
d    0.564171
e   -0.690476
dtype: float64

In [231]:
s1 = s[:4]

In [232]:
s2 = s[1:]

In [233]:
s1.align(s2)

(a    0.874135
 b    0.681662
 c    1.206386
 d    0.564171
 e         NaN
 dtype: float64, a         NaN
 b    0.681662
 c    1.206386
 d    0.564171
 e   -0.690476
 dtype: float64)

In [234]:
s1.align(s2, join='inner')

(b    0.681662
 c    1.206386
 d    0.564171
 dtype: float64, b    0.681662
 c    1.206386
 d    0.564171
 dtype: float64)

In [235]:
s1.align(s2, join='left')

(a    0.874135
 b    0.681662
 c    1.206386
 d    0.564171
 dtype: float64, a         NaN
 b    0.681662
 c    1.206386
 d    0.564171
 dtype: float64)

### 10.2 Filling while reindexing

In [236]:
rng = pd.date_range('1/3/2000', periods=8); rng

DatetimeIndex(['2000-01-03', '2000-01-04', '2000-01-05', '2000-01-06',
               '2000-01-07', '2000-01-08', '2000-01-09', '2000-01-10'],
              dtype='datetime64[ns]', freq='D')

In [237]:
ts = pd.Series(np.random.randn(8), index=rng); ts

2000-01-03    0.699587
2000-01-04    0.403661
2000-01-05   -0.895015
2000-01-06    1.414399
2000-01-07   -0.087811
2000-01-08    1.508025
2000-01-09   -0.219528
2000-01-10    1.242487
Freq: D, dtype: float64

In [238]:
ts2 = ts[[0,3,6]]; ts2

2000-01-03    0.699587
2000-01-06    1.414399
2000-01-09   -0.219528
dtype: float64

In [239]:
ts2.reindex(ts.index)

2000-01-03    0.699587
2000-01-04         NaN
2000-01-05         NaN
2000-01-06    1.414399
2000-01-07         NaN
2000-01-08         NaN
2000-01-09   -0.219528
2000-01-10         NaN
Freq: D, dtype: float64

In [240]:
ts2.reindex(ts.index, method='ffill')

2000-01-03    0.699587
2000-01-04    0.699587
2000-01-05    0.699587
2000-01-06    1.414399
2000-01-07    1.414399
2000-01-08    1.414399
2000-01-09   -0.219528
2000-01-10   -0.219528
Freq: D, dtype: float64

In [241]:
ts2.reindex(ts.index, method='bfill')

2000-01-03    0.699587
2000-01-04    1.414399
2000-01-05    1.414399
2000-01-06    1.414399
2000-01-07   -0.219528
2000-01-08   -0.219528
2000-01-09   -0.219528
2000-01-10         NaN
Freq: D, dtype: float64

In [242]:
ts2.reindex(ts.index, method='nearest')

2000-01-03    0.699587
2000-01-04    0.699587
2000-01-05    1.414399
2000-01-06    1.414399
2000-01-07    1.414399
2000-01-08   -0.219528
2000-01-09   -0.219528
2000-01-10   -0.219528
Freq: D, dtype: float64

In [243]:
ts2.reindex(ts.index).fillna(method='ffill')

2000-01-03    0.699587
2000-01-04    0.699587
2000-01-05    0.699587
2000-01-06    1.414399
2000-01-07    1.414399
2000-01-08    1.414399
2000-01-09   -0.219528
2000-01-10   -0.219528
Freq: D, dtype: float64

### 10.3 Limits on filling while reindexing

In [244]:
ts2.reindex(ts.index)

2000-01-03    0.699587
2000-01-04         NaN
2000-01-05         NaN
2000-01-06    1.414399
2000-01-07         NaN
2000-01-08         NaN
2000-01-09   -0.219528
2000-01-10         NaN
Freq: D, dtype: float64

In [245]:
ts2.reindex(ts.index, method='ffill', limit=1)

2000-01-03    0.699587
2000-01-04    0.699587
2000-01-05         NaN
2000-01-06    1.414399
2000-01-07    1.414399
2000-01-08         NaN
2000-01-09   -0.219528
2000-01-10   -0.219528
Freq: D, dtype: float64

In [246]:
ts2.reindex(ts.index, method='ffill', tolerance='1 day')

2000-01-03    0.699587
2000-01-04    0.699587
2000-01-05         NaN
2000-01-06    1.414399
2000-01-07    1.414399
2000-01-08         NaN
2000-01-09   -0.219528
2000-01-10   -0.219528
Freq: D, dtype: float64

### 10.4 Dropping labels from an axis

In [247]:
df

one     three       two
a  0.251360       NaN  0.175308
b -0.415292 -0.248493 -0.860320
c -0.761420  0.430212 -1.153337
d       NaN  0.664440  0.012675

In [248]:
df.drop(['a', 'b'], axis=0)

one     three       two
c -0.76142  0.430212 -1.153337
d      NaN  0.664440  0.012675

In [249]:
df.drop(['one'], axis=1)

three       two
a       NaN  0.175308
b -0.248493 -0.860320
c  0.430212 -1.153337
d  0.664440  0.012675

In [250]:
df.reindex(df.index.difference(['a', 'd']))

one     three       two
b -0.415292 -0.248493 -0.860320
c -0.761420  0.430212 -1.153337

### 10.5 Renaming / mapping labels

In [251]:
s

a    0.874135
b    0.681662
c    1.206386
d    0.564171
e   -0.690476
dtype: float64

In [253]:
s.rename(str.upper)

A    0.874135
B    0.681662
C    1.206386
D    0.564171
E   -0.690476
dtype: float64

In [254]:
df.rename(columns={'one': 'foo', 'two': 'bar'},
         index={'a': 'apple', 'b': 'banana', 'd': 'durian'})

foo     three       bar
apple   0.251360       NaN  0.175308
banana -0.415292 -0.248493 -0.860320
c      -0.761420  0.430212 -1.153337
durian       NaN  0.664440  0.012675

# 11 Iteration

In [256]:
df = pd.DataFrame({
    'col1': np.random.randn(3),
    'col2': np.random.randn(3)},
    index=['a', 'b', 'c']
)

In [257]:
for col in df:
    print(col)

col1
col2


In [258]:
df = pd.DataFrame({'a': [1, 2, 3], 'b':['a','d', 'c']})

In [260]:
for index, row in df.iterrows():
    row['a'] = 10

In [261]:
df

a  b
0  1  a
1  2  d
2  3  c

### 11.1 iteritems

In [262]:
wp

<class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 5 (major_axis) x 4 (minor_axis)
Items axis: Item1 to Item2
Major_axis axis: 2000-01-01 00:00:00 to 2000-01-05 00:00:00
Minor_axis axis: A to D

In [263]:
for item, frame in wp.iteritems():
    print(item)
    print(frame)

Item1
                   A         B         C         D
2000-01-01 -0.731890  3.942470  0.887984 -0.396483
2000-01-02  1.532735 -0.093738 -1.349553 -0.918516
2000-01-03 -1.926646  0.731153  1.971693 -1.064820
2000-01-04  0.919012  1.718347  0.022188  0.076233
2000-01-05  1.156729 -0.569005 -1.346334  0.632299
Item2
                   A         B         C         D
2000-01-01  2.026684 -1.283417 -0.317899 -0.683335
2000-01-02 -0.506782 -1.111691  2.095236  0.103885
2000-01-03 -0.589675  0.427160  0.198182  0.284747
2000-01-04 -0.741161 -0.754750 -0.288314  0.478627
2000-01-05 -1.213338 -0.925516 -0.373217  0.349775


### 11.2 iterrows

In [264]:
df

a  b
0  1  a
1  2  d
2  3  c

In [265]:
for row_index, row in df.iterrows():
    print('%s\n%s' % (row_index, row))

0
a    1
b    a
Name: 0, dtype: object
1
a    2
b    d
Name: 1, dtype: object
2
a    3
b    c
Name: 2, dtype: object


### 11.4 itertuples

In [266]:
for row in df.itertuples():
    print(row)

Pandas(Index=0, a=1, b='a')
Pandas(Index=1, a=2, b='d')
Pandas(Index=2, a=3, b='c')


### 11.3 .dt accessor

In [267]:
s = pd.Series(pd.date_range('20130101 09:10:12', periods=4)); s

0   2013-01-01 09:10:12
1   2013-01-02 09:10:12
2   2013-01-03 09:10:12
3   2013-01-04 09:10:12
dtype: datetime64[ns]

In [273]:
s.dt.hour

0    9
1    9
2    9
3    9
dtype: int64

In [274]:
s.dt.second

0    12
1    12
2    12
3    12
dtype: int64

In [275]:
s.dt.day

0    1
1    2
2    3
3    4
dtype: int64

In [276]:
s[s.dt.day==2]

1   2013-01-02 09:10:12
dtype: datetime64[ns]

In [277]:
stz = s.dt.tz_localize('US/Eastern')

In [278]:
stz

0   2013-01-01 09:10:12-05:00
1   2013-01-02 09:10:12-05:00
2   2013-01-03 09:10:12-05:00
3   2013-01-04 09:10:12-05:00
dtype: datetime64[ns, US/Eastern]

In [279]:
stz.dt.tz

<DstTzInfo 'US/Eastern' LMT-1 day, 19:04:00 STD>

In [280]:
#DateTimeIndex
s = pd.Series(pd.date_range('20130101', periods=4)); s

0   2013-01-01
1   2013-01-02
2   2013-01-03
3   2013-01-04
dtype: datetime64[ns]

In [282]:
s.dt.strftime('%Y/%m/%d') # formatação muito útil

0    2013/01/01
1    2013/01/02
2    2013/01/03
3    2013/01/04
dtype: object

In [284]:
#PeriodoIndex
s = pd.Series(pd.period_range('20130101', periods=4)); s

0   2013-01-01
1   2013-01-02
2   2013-01-03
3   2013-01-04
dtype: object

In [285]:
s.dt.strftime('%Y/%m/%d')

0    2013/01/01
1    2013/01/02
2    2013/01/03
3    2013/01/04
dtype: object

In [287]:
#Period
s = pd.Series(pd.period_range('20130101', periods=4, freq='D')); s

0   2013-01-01
1   2013-01-02
2   2013-01-03
3   2013-01-04
dtype: object

In [289]:
s.dt.year

0    2013
1    2013
2    2013
3    2013
dtype: int64

In [290]:
s.dt.day

0    1
1    2
2    3
3    4
dtype: int64

In [291]:
# Timedelta
s = pd.Series(pd.timedelta_range('1 day 00:00:05', periods=4, freq='s')); s

0   1 days 00:00:05
1   1 days 00:00:06
2   1 days 00:00:07
3   1 days 00:00:08
dtype: timedelta64[ns]

In [292]:
s.dt.days

0    1
1    1
2    1
3    1
dtype: int64

In [293]:
s.dt.seconds

0    5
1    6
2    7
3    8
dtype: int64

In [294]:
s.dt.components

days  hours  minutes  seconds  milliseconds  microseconds  nanoseconds
0     1      0        0        5             0             0            0
1     1      0        0        6             0             0            0
2     1      0        0        7             0             0            0
3     1      0        0        8             0             0            0

### 11.4 Vectorized string methods

In [297]:
s = pd.Series(['A', 'B', 'C', 'Aaba', 'Baca', np.nan, 'CABA', 'dog', 'cat']); s

0       A
1       B
2       C
3    Aaba
4    Baca
5     NaN
6    CABA
7     dog
8     cat
dtype: object

In [298]:
s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: object

In [299]:
s.str.upper()

0       A
1       B
2       C
3    AABA
4    BACA
5     NaN
6    CABA
7     DOG
8     CAT
dtype: object

## 11.5 Sorting

### 11.6.1 By Index

In [302]:
unsorted_df = df.reindex(index=['a', 'd', 'c', 'b'], columns=['three', 'two', 'one'])

In [304]:
unsorted_df.sort_index()

three  two  one
a    NaN  NaN  NaN
b    NaN  NaN  NaN
c    NaN  NaN  NaN
d    NaN  NaN  NaN

In [305]:
unsorted_df.sort_index(ascending=False)

three  two  one
d    NaN  NaN  NaN
c    NaN  NaN  NaN
b    NaN  NaN  NaN
a    NaN  NaN  NaN

In [306]:
unsorted_df.sort_index(axis=1)

one  three  two
a  NaN    NaN  NaN
d  NaN    NaN  NaN
c  NaN    NaN  NaN
b  NaN    NaN  NaN

In [307]:
unsorted_df.sort_index(ascending=False, axis=1)

two  three  one
a  NaN    NaN  NaN
d  NaN    NaN  NaN
c  NaN    NaN  NaN
b  NaN    NaN  NaN

In [308]:
unsorted_df['three'].sort_index()

a   NaN
b   NaN
c   NaN
d   NaN
Name: three, dtype: float64

### 11.6.2 By Values

In [310]:
df1 = pd.DataFrame({
    'one': [2, 1, 1, 1],
    'two': [1, 3, 2, 4],
    'three': [5, 4, 3, 2]
})
df1

one  three  two
0    2      5    1
1    1      4    3
2    1      3    2
3    1      2    4

In [311]:
df1.sort_values(by='two')

one  three  two
0    2      5    1
2    1      3    2
1    1      4    3
3    1      2    4

In [312]:
df1[['one', 'two', 'three']].sort_values(by=['one', 'two'])

one  two  three
2    1    2      3
1    1    3      4
3    1    4      2
0    2    1      5

In [314]:
s[2] = np.nan

In [315]:
s.sort_values()

0       A
3    Aaba
1       B
4    Baca
6    CABA
8     cat
7     dog
2     NaN
5     NaN
dtype: object

In [316]:
s.sort_values(na_position='first')

2     NaN
5     NaN
0       A
3    Aaba
1       B
4    Baca
6    CABA
8     cat
7     dog
dtype: object

### 11.6.3 searchsorted

In [317]:
ser = pd.Series([1, 2, 3]); ser

0    1
1    2
2    3
dtype: int64

In [318]:
ser.searchsorted([0, 3])

array([0, 2], dtype=int64)

In [319]:
ser.searchsorted([0, 4])

array([0, 3], dtype=int64)

In [320]:
ser.searchsorted([1, 4], side='right')

array([1, 3], dtype=int64)

In [321]:
ser.searchsorted([1, 4], side='left')

array([0, 3], dtype=int64)

In [323]:
ser = pd.Series([3, 1, 2])
ser.searchsorted([0, 3], sorter=np.argsort(ser))

array([0, 2], dtype=int64)

### 11.6.4 smallest / largest values

In [324]:
s = pd.Series(np.random.permutation(10))
s

0    6
1    7
2    1
3    5
4    3
5    0
6    9
7    4
8    8
9    2
dtype: int32

In [325]:
s.sort_values()

5    0
2    1
9    2
4    3
7    4
3    5
0    6
1    7
8    8
6    9
dtype: int32

In [326]:
s.nsmallest(3)  # Retorna os 3 menores

5    0
2    1
9    2
dtype: int32

In [328]:
s.nlargest(3) # Retorna os 3 maiores

6    9
8    8
1    7
dtype: int32

In [331]:
df = pd.DataFrame({
    'a': [-2, -1, 1, 10, 8, 11, -1],
    'b': list('abcdeff'),
    'c': [1.0, 2.0, 4.0, 3.2, np.nan, 3.0, 4.0]
})
df

a  b    c
0  -2  a  1.0
1  -1  b  2.0
2   1  c  4.0
3  10  d  3.2
4   8  e  NaN
5  11  f  3.0
6  -1  f  4.0

In [333]:
df.nlargest(3, 'a') # nlargest(quantidade, coluna)

a  b    c
5  11  f  3.0
3  10  d  3.2
4   8  e  NaN

In [336]:
df.nlargest(5,['a', 'c'])

a  b    c
6  -1  f  4.0
5  11  f  3.0
3  10  d  3.2
4   8  e  NaN
2   1  c  4.0

In [337]:
df.nsmallest(3, 'a') # nsmallest(quantidade, coluna)

a  b    c
0 -2  a  1.0
1 -1  b  2.0
6 -1  f  4.0

In [338]:
df.nsmallest(5,['a', 'c'])

a  b    c
0 -2  a  1.0
2  1  c  4.0
4  8  e  NaN
1 -1  b  2.0
6 -1  f  4.0

### 11.6.5 Sorting by a mult-index column

In [339]:
df1

one  three  two
0    2      5    1
1    1      4    3
2    1      3    2
3    1      2    4

In [340]:
df1.columns = pd.MultiIndex.from_tuples([
    ('a', 'one'), ('a', 'two'), ('b', 'three')
])

In [345]:
df1.sort_values(by=('a', 'two'))

a         b
  one two three
3   1   2     4
2   1   3     2
1   1   4     3
0   2   5     1

In [347]:
type(df1.index)

pandas.core.indexes.range.RangeIndex

In [348]:
df3

A
e  2.0
d  1.0
c  1.0
b  3.0
a  NaN